train_file: data/ArchiveII/ArchiveII_seq_sim_pp_motifs/train_0.csv
valid_file: data/ArchiveII/ArchiveII_seq_sim_pp_motifs/valid_0.csv
out_path: results/${exp}/${run}/
continue_training: false
train_swaps: 0
